### ISSUE TITLE
Project Files

### ISSUE THREAD

**Issue by YoOli88** [userexit/Fungal-UI#1]
Hello, i want to use this simple UI framework in a project of mine. I did all the steps of your documentation but the compiler version is different and therefore it doesnt work correctly. I tried to build the libfiles myself from the source files but it spits out a bunch of errors, so i wanted to kindly ask if you could upload the complete files needed for building it with VisualStudio or Cmake.
thanks in advance.

**Comment by user-simon** [comment]
I added some lazily omitted CMake files, let me know if it works now!

**Comment by user-simon** [comment]
Also, what compiler and C++ version are you using?
